### ISSUE TITLE
 OUT TOPIC - sorry - 

### ISSUE THREAD

**Issue by merlino1975** [davet2001/home-assistant-addons#58]
Scuse me, I don't know how use this platform. I've a request for the AURORA POWEONE inveter integration HOMASS. but I don't find where write for this: I would like if is possible to integrate your integration and the ELFIN ew11 (wifi trasmission)...is possible connect?
I cannot use a usb-rs845 connector but I can connect this modbus called elfin ew11... do you know him?
thanks!

**Comment by davet2001** [comment]
Hi @merlino1975 this is not the correct place to raise a request for aurora_abb_powerone but, you could do that via the home assistant community forums.

I think the adding modbusTCP would probably be the first step before wifi, but I expect all are possible.

**Comment by merlino1975** [comment]
scuse me again, but this integration https://www.home-assistant.io/integrations/aurora_abb_powerone/#configuration have your name...and I nont find your project... the ew11 now works in wifi.. protococol tcp...so I must to ask in home assistant comunity...well...I'll do it thanks!Inviato dal mio Galaxy
-------- Messaggio originale --------Da: Dave T ***@***.***> Data: 30/07/24  13:59  (GMT+01:00) A: davet2001/home-assistant-addons ***@***.***> Cc: merlino1975 ***@***.***>, Mention ***@***.***> Oggetto: Re: [davet2001/home-assistant-addons]  OUT TOPIC - sorry -  (Issue
  #58) 
Hi @merlino1975 this is not the correct place to raise a request for aurora_abb_powerone but, you could do that via the home assistant community forums.
I think the adding modbusTCP would probably be the first step before wifi, but I expect all are possible.
